// Generated by gencpp from file communication_package/DivisionResponse.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_PACKAGE_MESSAGE_DIVISIONRESPONSE_H
#define COMMUNICATION_PACKAGE_MESSAGE_DIVISIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_package
{
template <class ContainerAllocator>
struct DivisionResponse_
{
  typedef DivisionResponse_<ContainerAllocator> Type;

  DivisionResponse_()
    : result(0.0)
    , success(false)  {
    }
  DivisionResponse_(const ContainerAllocator& _alloc)
    : result(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _result_type;
  _result_type result;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::communication_package::DivisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_package::DivisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DivisionResponse_

typedef ::communication_package::DivisionResponse_<std::allocator<void> > DivisionResponse;

typedef boost::shared_ptr< ::communication_package::DivisionResponse > DivisionResponsePtr;
typedef boost::shared_ptr< ::communication_package::DivisionResponse const> DivisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_package::DivisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_package::DivisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication_package::DivisionResponse_<ContainerAllocator1> & lhs, const ::communication_package::DivisionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication_package::DivisionResponse_<ContainerAllocator1> & lhs, const ::communication_package::DivisionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communication_package::DivisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_package::DivisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_package::DivisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_package::DivisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_package::DivisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_package::DivisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_package::DivisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ead7e9fea50afbeb07b532762de132d2";
  }

  static const char* value(const ::communication_package::DivisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xead7e9fea50afbebULL;
  static const uint64_t static_value2 = 0x07b532762de132d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_package::DivisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_package/DivisionResponse";
  }

  static const char* value(const ::communication_package::DivisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_package::DivisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 result\n"
"bool success\n"
;
  }

  static const char* value(const ::communication_package::DivisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_package::DivisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DivisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_package::DivisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_package::DivisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_PACKAGE_MESSAGE_DIVISIONRESPONSE_H
