// Generated by gencpp from file communication_package/Person.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_PACKAGE_MESSAGE_PERSON_H
#define COMMUNICATION_PACKAGE_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_package
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , age(0)
    , gender(false)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , gender(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint8_t _gender_type;
  _gender_type gender;





  typedef boost::shared_ptr< ::communication_package::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_package::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::communication_package::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::communication_package::Person > PersonPtr;
typedef boost::shared_ptr< ::communication_package::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_package::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_package::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication_package::Person_<ContainerAllocator1> & lhs, const ::communication_package::Person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.gender == rhs.gender;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication_package::Person_<ContainerAllocator1> & lhs, const ::communication_package::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communication_package::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_package::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_package::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_package::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_package::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_package::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_package::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "514351469df485dedb4099f5454028df";
  }

  static const char* value(const ::communication_package::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x514351469df485deULL;
  static const uint64_t static_value2 = 0xdb4099f5454028dfULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_package::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_package/Person";
  }

  static const char* value(const ::communication_package::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_package::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint8 age\n"
"bool gender\n"
;
  }

  static const char* value(const ::communication_package::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_package::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.gender);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_package::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_package::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "gender: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gender);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_PACKAGE_MESSAGE_PERSON_H
